import { Pokemon } from "../pokemon/pokemon";
import { PokemonType } from "../pokemon/pokemon-type";
import { PokemonAlignment } from "../pokemon/pokemon-alignment";
import { PokemonMovement } from "../pokemon/pokemon-movement";
import { PokemonSpecialAbility } from "../pokemon/pokemon-specialability";
import { PokemonSpecialDefense } from "../pokemon/pokemon-specialdefense";

export const POKEMONS: Pokemon[] = [
    {
        id: 1,
        name: "Pichu",
        description: "Pichu est une petite souris. Il est jaune avec le bout des oreilles noir, ainsi que la queue et le cou. Ses joues sont rose foncé. Il frappe ses opposants en leur donnant de petites décharges électriques grâce à sa queue.",
        level: 1,
        type: PokemonType.animal,
        subType: "Souris",
        alignment: PokemonAlignment.good,
        size: 10,
        weight: 1,
        hitPoints: 20,
        protection: 0,
        movement: PokemonMovement.normal,
        attack: 2,
        damage: 1,
        defense: 12,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.electricity, damage: 2 }
        ],
        specialDefense: PokemonSpecialDefense.electricity,
        picture: "assets/pokemons/Pichu.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 2,
        name: "Pikachu",
        description: "Pikachu est une souris au pelage jaune et aux joues rouges, capable de projeter des éclairs. Il a cinq petits doigts au bout de chacun de ses membres antérieurs.",
        level: 2,
        type: PokemonType.animal,
        subType: "Souris",
        alignment: PokemonAlignment.good,
        size: 30,
        weight: 3,
        hitPoints: 40,
        protection: 1,
        movement: PokemonMovement.normal,
        attack: 5,
        damage: 2,
        defense: 13,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.lightning, damage: 4 }
        ],
        specialDefense: PokemonSpecialDefense.electricity,
        picture: "assets/pokemons/Pikachu.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 3,
        name: "Pikachu",
        description: "Pikachu est une souris au pelage jaune et aux joues rouges, capable de projeter des éclairs. Il a cinq petits doigts au bout de chacun de ses membres antérieurs.",
        level: 3,
        type: PokemonType.animal,
        subType: "Souris",
        alignment: PokemonAlignment.good,
        size: 30,
        weight: 3,
        hitPoints: 60,
        protection: 1,
        movement: PokemonMovement.normal,
        attack: 8,
        damage: 2,
        defense: 14,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.lightning, damage: 4 },
            { specialAbility: PokemonSpecialAbility.electricArc, damage: 7, times: 2 }
        ],
        specialDefense: PokemonSpecialDefense.electricity,
        picture: "assets/pokemons/Pikachu.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 4,
        name: "Raichu",
        description: "Raichu est une grosse souris au pelage orange avec un ventre blanc, capable de projeter des éclairs. Il possède une longue queue noire avec au bout un éclair jaune.",
        level: 4,
        type: PokemonType.animal,
        subType: "Souris",
        alignment: PokemonAlignment.good,
        size: 60,
        weight: 6,
        hitPoints: 80,
        protection: 2,
        movement: PokemonMovement.normal,
        attack: 10,
        damage: 2,
        defense: 15,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.lightning, damage: 4 },
            { specialAbility: PokemonSpecialAbility.electricArc, damage: 7, times: 2 },
            { specialAbility: PokemonSpecialAbility.lightningChain, damage: 10, times: 1 }
        ],
        specialDefense: PokemonSpecialDefense.electricity,
        picture: "assets/pokemons/Raichu.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 5,
        name: "Goupix",
        description: "Ce renard roux à plusieurs queues est capable de brûler ses opposants en les touchant. Il a de grands yeux noisette, des oreilles pointues à l'intérieur brun et un petit museau brun.",
        level: 1,
        type: PokemonType.animal,
        subType: "Renard",
        alignment: PokemonAlignment.good,
        size: 90,
        weight: 10,
        hitPoints: 30,
        protection: 2,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 2,
        defense: 9,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.fire, damage: 2 }
        ],
        specialDefense: PokemonSpecialDefense.fire,
        picture: "assets/pokemons/Goupix.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 6,
        name: "Goupix",
        description: "Ce renard roux à plusieurs queues est capable de brûler ses opposants en les touchant. Il a de grands yeux noisette, des oreilles pointues à l'intérieur brun et un petit museau brun.",
        level: 2,
        type: PokemonType.animal,
        subType: "Renard",
        alignment: PokemonAlignment.good,
        size: 120,
        weight: 15,
        hitPoints: 60,
        protection: 3,
        movement: PokemonMovement.normal,
        attack: 5,
        damage: 2,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.fire, damage: 2 }
        ],
        specialDefense: PokemonSpecialDefense.fire,
        picture: "assets/pokemons/Goupix.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 7,
        name: "Feunard",
        description: "Feunard est un grand renard couleur crème. Il est inspiré d'une créature légendaire, le renard à neuf queues. Il posséde des pouvoirs mystiques qui lui procurent notamment une longévité de 1 000 ans.",
        level: 3,
        type: PokemonType.animal,
        subType: "Renard",
        alignment: PokemonAlignment.good,
        size: 150,
        weight: 20,
        hitPoints: 90,
        protection: 4,
        movement: PokemonMovement.normal,
        attack: 6,
        damage: 2,
        defense: 11,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.intenseFire, damage: 4 },
            { specialAbility: PokemonSpecialAbility.psionist, damage: 3, attack: 2 },
        ],
        specialDefense: PokemonSpecialDefense.fire,
        picture: "assets/pokemons/Feunard.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 8,
        name: "Feunard",
        description: "Feunard est un grand renard couleur crème. Il est inspiré d'une créature légendaire, le renard à neuf queues. Il posséde des pouvoirs mystiques qui lui procurent notamment une longévité de 1 000 ans.",
        level: 4,
        type: PokemonType.animal,
        subType: "Renard",
        alignment: PokemonAlignment.good,
        size: 180,
        weight: 30,
        hitPoints: 120,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 7,
        damage: 2,
        defense: 12,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.intenseFire, damage: 4 },
            { specialAbility: PokemonSpecialAbility.psionist, damage: 3, attack: 2 },
            { specialAbility: PokemonSpecialAbility.psychicShield, defense: 4 },
        ],
        specialDefense: PokemonSpecialDefense.fire,
        picture: "assets/pokemons/Feunard.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 9,
        name: "Mélo",
        description: "Mélo ressemble à une miniature de Mélofée en forme d'étoile. Ses joues sont rouges et sa peau rose. Il a aussi une petite mèche.",
        level: 1,
        type: PokemonType.fey,
        subType: "Fée",
        alignment: PokemonAlignment.good,
        size: 50,
        weight: 6,
        hitPoints: 25,
        protection: 0,
        movement: PokemonMovement.fly,
        attack: 8,
        damage: 1,
        defense: 16,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.apprenticeMagicUser, damage: 2 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Mélo.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 10,
        name: "Mélofée",
        description: "Ce Pokémon est extrêmement intelligent. Il a la fourrure rase et rose, avec deux oreilles dressées.",
        level: 2,
        type: PokemonType.fey,
        subType: "Fée",
        alignment: PokemonAlignment.good,
        size: 50,
        weight: 6,
        hitPoints: 25,
        protection: 0,
        movement: PokemonMovement.fly,
        attack: 8,
        damage: 1,
        defense: 16,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.magicUser, damage: 3, defense: 1 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Mélofée.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 11,
        name: "Mélofée",
        description: "Ce Pokémon est extrêmement intelligent. Il a la fourrure rase et rose, avec deux oreilles dressées.",
        level: 3,
        type: PokemonType.fey,
        subType: "Fée",
        alignment: PokemonAlignment.good,
        size: 50,
        weight: 6,
        hitPoints: 25,
        protection: 0,
        movement: PokemonMovement.fly,
        attack: 8,
        damage: 1,
        defense: 16,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.mage, damage: 4, defense: 2 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Mélofée.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 12,
        name: "Mélodelfe",
        description: "Mélodelfe est assez similaire à Mélofée, bien qu'elle soit un peu plus grande. Ses ailes ont grandi et sont devenues d'un rose plus intense.",
        level: 4,
        type: PokemonType.fey,
        subType: "Fée",
        alignment: PokemonAlignment.good,
        size: 50,
        weight: 6,
        hitPoints: 25,
        protection: 0,
        movement: PokemonMovement.fly,
        attack: 8,
        damage: 1,
        defense: 16,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.archmage, damage: 4, defense: 4 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Mélodelfe.png",
        created: new Date(),
        updated: undefined
    },


    {
        id: 13,
        name: "Aspicot",
        description: "Aspicot est à moitié chenille et à moitié asticot. Sa tête et sa queue sont dotés d'un aiguillon empoisonné.",
        level: 1,
        type: PokemonType.vermin,
        subType: "Guêpe",
        alignment: PokemonAlignment.neutral,
        size: 20,
        weight: 0.4,
        hitPoints: 10,
        protection: 0,
        movement: PokemonMovement.normal,
        attack: 2,
        damage: 1,
        defense: 5,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.poison, damage: 3 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Aspicot.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 14,
        name: "Coconfort",
        description: "Coconfort est en fait un Pokémon enveloppé dans une armure marron clair attendant son évolution. Il est inspiré d'une nymphe de guêpe, c'est-à-dire son stade entre la larve et l'adulte.",
        level: 2,
        type: PokemonType.vermin,
        subType: "Guêpe",
        alignment: PokemonAlignment.neutral,
        size: 50,
        weight: 2.5,
        hitPoints: 20,
        protection: 6,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 2,
        defense: 0,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.virulentPoison, damage: 5 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Coconfort.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 15,
        name: "Dardargnan",
        description: "Dardargnan est un Pokémon inspiré de la guêpe géante du Japon, le vespa mandarinia. Il est jaune et noir et possède quatre pattes dont les deux antérieures sont munies de gros dards.",
        level: 3,
        type: PokemonType.vermin,
        subType: "Guêpe",
        alignment: PokemonAlignment.neutral,
        size: 100,
        weight: 8,
        hitPoints: 50,
        protection: 2,
        movement: PokemonMovement.fly,
        attack: 7,
        damage: 3,
        defense: 12,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.deadlyPoison, damage: 5 },
            { specialAbility: PokemonSpecialAbility.fighter, damage: 2, attack: 2 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Dardargnan.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 16,
        name: "Méga-Dardargnan",
        description: "Le Méga-Dardargnan est un Dardagnan extrêmement aggressif. Son abdomen se modèle pour accueillir ses pattes inférieures lorsqu'il passe en position d'attaque, pour ne former qu'un seul et puissant dard",
        level: 4,
        type: PokemonType.vermin,
        subType: "Guêpe",
        alignment: PokemonAlignment.neutral,
        size: 150,
        weight: 12,
        hitPoints: 100,
        protection: 2,
        movement: PokemonMovement.fly,
        attack: 10,
        damage: 4,
        defense: 12,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.deadlyPoison, damage: 5 },
            { specialAbility: PokemonSpecialAbility.masterSwordsman, damage: 3, attack: 4 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Méga-Dardargnan.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 17,
        name: "Limagma",
        description: "Limagma ressemble à une limace de lave ; il n'a donc ni bras ni jambe et se déplace en rampant. Son corps rouge orangé, à l'apparence visqueuse, est parsemé de bulles de magma en fusion. Il a de grands yeux jaunes ovales avec de petites pupilles noires, surmontés de flammes.",
        level: 1,
        type: PokemonType.elemental,
        subType: "Élémentaire de magma",
        alignment: PokemonAlignment.neutral,
        size: 80,
        weight: 40,
        hitPoints: 50,
        protection: 2,
        movement: PokemonMovement.normal,
        attack: 2,
        damage: 2,
        defense: 7,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.intenseFire, damage: 4 }
        ],
        specialDefense: PokemonSpecialDefense.fire,
        picture: "assets/pokemons/Limagma.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 18,
        name: "Limagma",
        description: "Limagma ressemble à une limace de lave ; il n'a donc ni bras ni jambe et se déplace en rampant. Son corps rouge orangé, à l'apparence visqueuse, est parsemé de bulles de magma en fusion. Il a de grands yeux jaunes ovales avec de petites pupilles noires, surmontés de flammes.",
        level: 2,
        type: PokemonType.elemental,
        subType: "Élémentaire de magma",
        alignment: PokemonAlignment.neutral,
        size: 120,
        weight: 60,
        hitPoints: 100,
        protection: 2,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 7,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.intenseFire, damage: 4 }
        ],
        specialDefense: PokemonSpecialDefense.fire,
        picture: "assets/pokemons/Limagma.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 19,
        name: "Volcaropod",
        description: "Volcaropod est un gastéropode, et plus précisément un escargot de feu, qui doit son nom à sa couleur rouge. Son corps rouge orangé et visqueux est fait de lave. Il est doté d'une coquille de roche volcanique.",
        level: 3,
        type: PokemonType.elemental,
        subType: "Élémentaire de magma",
        alignment: PokemonAlignment.neutral,
        size: 160,
        weight: 120,
        hitPoints: 150,
        protection: 4,
        movement: PokemonMovement.normal,
        attack: 6,
        damage: 4,
        defense: 8,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.intenseFire, damage: 4 }
        ],
        specialDefense: PokemonSpecialDefense.fire,
        picture: "assets/pokemons/Volcaropod.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 20,
        name: "Volcaropod",
        description: "Volcaropod est un gastéropode, et plus précisément un escargot de feu, qui doit son nom à sa couleur rouge. Son corps rouge orangé et visqueux est fait de lave. Il est doté d'une coquille de roche volcanique.",
        level: 4,
        type: PokemonType.elemental,
        subType: "Élémentaire de magma",
        alignment: PokemonAlignment.neutral,
        size: 200,
        weight: 150,
        hitPoints: 200,
        protection: 4,
        movement: PokemonMovement.normal,
        attack: 8,
        damage: 5,
        defense: 8,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.intenseFire, damage: 4 }
        ],
        specialDefense: PokemonSpecialDefense.fire,
        picture: "assets/pokemons/Volcaropod.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 21,
        name: "Bulbizarre",
        description: "Ce petit quadrupède vert d'origine végétale porte un bulbe contenant de l'acide sur son dos.",
        level: 1,
        type: PokemonType.plant,
        subType: "Bulbe",
        alignment: PokemonAlignment.neutral,
        size: 70,
        weight: 6.5,
        hitPoints: 30,
        protection: 4,
        movement: PokemonMovement.normal,
        attack: 6,
        damage: 2,
        defense: 12,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.benignPoison, damage: 1 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Bulbizarre.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 22,
        name: "Herbizarre",
        description: "Herbizarre est un Pokémon quadrupède, semblable à un dinosaure. Il a un corps bleu vert avec des taches plus foncées. Le bulbe sur son dos a fleuri et est devenu un gros bourgeon rose dont le poids est tel qu'il empêche Herbizarre de se tenir sur ses pattes postérieures.",
        level: 2,
        type: PokemonType.plant,
        subType: "Bulbe",
        alignment: PokemonAlignment.neutral,
        size: 70,
        weight: 6.5,
        hitPoints: 30,
        protection: 4,
        movement: PokemonMovement.normal,
        attack: 6,
        damage: 3,
        defense: 12,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.poison, damage: 3 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Herbizarre.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 23,
        name: "Herbizarre",
        description: "Herbizarre est un Pokémon quadrupède, semblable à un dinosaure. Il a un corps bleu vert avec des taches plus foncées. Le bulbe sur son dos a fleuri et est devenu un gros bourgeon rose dont le poids est tel qu'il empêche Herbizarre de se tenir sur ses pattes postérieures.",
        level: 3,
        type: PokemonType.plant,
        subType: "Bulbe",
        alignment: PokemonAlignment.neutral,
        size: 70,
        weight: 6.5,
        hitPoints: 30,
        protection: 4,
        movement: PokemonMovement.normal,
        attack: 6,
        damage: 3,
        defense: 12,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.virulentPoison, damage: 5 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Herbizarre.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 24,
        name: "Florizarre",
        description: "Florizarre est un imposant quadrupède à la peau verte ayant l'aspect d'un batracien, il est beaucoup plus grand et lourd que Bulbizarre et Herbizarre. Il porte une grande fleur rose tachetée sur son dos, entourée de quatre grandes feuilles.",
        level: 4,
        type: PokemonType.plant,
        subType: "Bulbe",
        alignment: PokemonAlignment.neutral,
        size: 70,
        weight: 6.5,
        hitPoints: 30,
        protection: 4,
        movement: PokemonMovement.normal,
        attack: 6,
        damage: 4,
        defense: 12,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.virulentPoison, damage: 5 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Florizarre.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 25,
        name: "Carapuce",
        description: "Carapuce est une tortue bipède de couleur bleue capable de cracher de l'eau.",
        level: 1,
        type: PokemonType.animal,
        subType: "Tortue",
        alignment: PokemonAlignment.neutral,
        size: 90,
        weight: 12,
        hitPoints: 50,
        protection: 8,
        movement: PokemonMovement.swim,
        attack: 4,
        damage: 3,
        defense: 8,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.fighter, damage: 1, attack: 2 },
            { specialAbility: PokemonSpecialAbility.heatWater, damage: 4 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Carapuce.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 26,
        name: "Carabaffe",
        description: "Carabaffe est une tortue bipède de couleur bleu indigo, dont les oreilles et la queue sont recouvertes d'une fourrure duveteuse de couleur blanche ; celle-ci fait d'ailleurs penser à des vagues. Il est capable de cracher de l'eau sur ses opposants.",
        level: 2,
        type: PokemonType.animal,
        subType: "Tortue",
        alignment: PokemonAlignment.neutral,
        size: 90,
        weight: 12,
        hitPoints: 50,
        protection: 8,
        movement: PokemonMovement.swim,
        attack: 4,
        damage: 4,
        defense: 8,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.expertFighter, damage: 2, attack: 3 },
            { specialAbility: PokemonSpecialAbility.heatWater, damage: 4 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Carabaffe.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 27,
        name: "Tortank",
        description: "Tortank est un bipède massif de la famille des tortues. Les extrémités supérieures gauche et droite de sa carapace sont ornées d'un canon à eau. Formé au combat, sa tête s'est endurcie. Il possède deux petites oreilles et une queue courte.",
        level: 3,
        type: PokemonType.animal,
        subType: "Tortue",
        alignment: PokemonAlignment.neutral,
        size: 90,
        weight: 12,
        hitPoints: 50,
        protection: 8,
        movement: PokemonMovement.swim,
        attack: 5,
        damage: 2,
        defense: 8,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.masterSwordsman, damage: 3, attack: 4 },
            { specialAbility: PokemonSpecialAbility.heatWater, damage: 4 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Tortank.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 28,
        name: "Méga-Tortank",
        description: "Méga-Tortank ressemble à Tortank. Le gros canon situé à l'avant de sa carapace lui permet de projeter de la vapeur brûlante.",
        level: 4,
        type: PokemonType.animal,
        subType: "Tortue",
        alignment: PokemonAlignment.neutral,
        size: 90,
        weight: 12,
        hitPoints: 50,
        protection: 8,
        movement: PokemonMovement.swim,
        attack: 5,
        damage: 2,
        defense: 8,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.champion, damage: 4, attack: 4 },
            { specialAbility: PokemonSpecialAbility.heatWater, damage: 4 },
            { specialAbility: PokemonSpecialAbility.burningVapors, damage: 10, times: 1 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Méga-Tortank.png",
        created: new Date(),
        updated: undefined
    },

    {
        id: 29,
        name: "Abo",
        description: "Abo est un serpent à sonnette au corps violet.",
        level: 1,
        type: PokemonType.animal,
        subType: "Serpent cracheur",
        alignment: PokemonAlignment.evil,
        size: 100,
        weight: 10.0,
        hitPoints: 20,
        protection: 1,
        movement: PokemonMovement.normal,
        attack: 3,
        damage: 2,
        defense: 8,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.benignPoison, damage: 1 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Abo.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 30,
        name: "Abo",
        description: "Abo est un serpent à sonnette au corps violet.",
        level: 2,
        type: PokemonType.animal,
        subType: "Serpent cracheur",
        alignment: PokemonAlignment.evil,
        size: 200,
        weight: 25.0,
        hitPoints: 40,
        protection: 2,
        movement: PokemonMovement.normal,
        attack: 5,
        damage: 2,
        defense: 9,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.poison, damage: 3 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Abo.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 31,
        name: "Arbok",
        description: "Arbok est un cobra au corps violet. Des études ont révélé que les marques effrayantes de son corps pouvaient former six motifs différents.",
        level: 3,
        type: PokemonType.animal,
        subType: "Serpent cracheur",
        alignment: PokemonAlignment.evil,
        size: 300,
        weight: 50.0,
        hitPoints: 80,
        protection: 3,
        movement: PokemonMovement.normal,
        attack: 7,
        damage: 3,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.fighter, damage: 1, attack: 2 },
            { specialAbility: PokemonSpecialAbility.virulentPoison, damage: 5 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Arbok.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 32,
        name: "Arbok",
        description: "Arbok est un cobra au corps violet. Des études ont révélé que les marques effrayantes de son corps pouvaient former six motifs différents.",
        level: 4,
        type: PokemonType.animal,
        subType: "Serpent cracheur",
        alignment: PokemonAlignment.evil,
        size: 400,
        weight: 75.0,
        hitPoints: 120,
        protection: 4,
        movement: PokemonMovement.normal,
        attack: 9,
        damage: 3,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.fighter, damage: 1, attack: 2 },
            { specialAbility: PokemonSpecialAbility.deadlyPoison, damage: 7 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Arbok.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 33,
        name: "Piafabec",
        description: "Petit et rapide, Piafabec est un petit rapace à la mine revêche doté d'un caractère désagréable.",
        level: 1,
        type: PokemonType.animal,
        subType: "Rapace",
        alignment: PokemonAlignment.evil,
        size: 30,
        weight: 1.5,
        hitPoints: 30,
        protection: 0,
        movement: PokemonMovement.fly,
        attack: 7,
        damage: 2,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.fighter, damage: 1, attack: 2 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Piafabec.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 34,
        name: "Piafabec",
        description: "Petit et rapide, Piafabec est un petit rapace à la mine revêche doté d'un caractère désagréable.",
        level: 2,
        type: PokemonType.animal,
        subType: "Rapace",
        alignment: PokemonAlignment.evil,
        size: 30,
        weight: 1.5,
        hitPoints: 30,
        protection: 0,
        movement: PokemonMovement.fly,
        attack: 7,
        damage: 2,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.fighter, damage: 1, attack: 2 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Piafabec.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 35,
        name: "Rapasdepic",
        description: "Rapasdepic est un rapace beige à crête rouge. Il a les yeux blancs avec des pupilles noires et possède un bec pointu et d'immenses ailes. Il a des serres puissantes. Il est craint de tous les Pokémon oiseaux plus petits que lui. Il aime  planer au-dessus des nuages, là où la plupart des oiseaux ne volent pas. ",
        level: 3,
        type: PokemonType.animal,
        subType: "Rapace",
        alignment: PokemonAlignment.evil,
        size: 30,
        weight: 1.5,
        hitPoints: 30,
        protection: 0,
        movement: PokemonMovement.fly,
        attack: 7,
        damage: 2,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.expertFighter, damage: 2, attack: 3 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Rapasdepic.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 36,
        name: "Rapasdepic",
        description: "Rapasdepic est un rapace beige à crête rouge. Il a les yeux blancs avec des pupilles noires et possède un bec pointu et d'immenses ailes. Il a des serres puissantes. Il est craint de tous les Pokémon oiseaux plus petits que lui. Il aime  planer au-dessus des nuages, là où la plupart des oiseaux ne volent pas. ",
        level: 4,
        type: PokemonType.animal,
        subType: "Rapace",
        alignment: PokemonAlignment.evil,
        size: 30,
        weight: 1.5,
        hitPoints: 30,
        protection: 0,
        movement: PokemonMovement.fly,
        attack: 7,
        damage: 2,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.expertFighter, damage: 2, attack: 3 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Rapasdepic.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 37,
        name: "Rattata",
        description: "Rattata est un Pokémon ressemblant à un rat au corps violet et blanc pâle. Il est très aggressif.",
        level: 1,
        type: PokemonType.animal,
        subType: "Rat",
        alignment: PokemonAlignment.evil,
        size: 50,
        weight: 3.5,
        hitPoints: 16,
        protection: 2,
        movement: PokemonMovement.normal,
        attack: 5,
        damage: 2,
        defense: 13,
        specialAbilities: [],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Rattata.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 38,
        name: "Rattata",
        description: "Rattata est un Pokémon ressemblant à un rat au corps violet et blanc pâle. Il est très aggressif.",
        level: 2,
        type: PokemonType.animal,
        subType: "Rat",
        alignment: PokemonAlignment.evil,
        size: 50,
        weight: 3.5,
        hitPoints: 16,
        protection: 2,
        movement: PokemonMovement.normal,
        attack: 5,
        damage: 2,
        defense: 13,
        specialAbilities: [],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Rattata.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 39,
        name: "Rattatac",
        description: "Rattatac ressemble à un gros rat et possède de petits bras, un corps marron et beige et des pieds palmés.. Rattatac est rapide et robuste, capable de s'attaquer à n'importe qui.",
        level: 3,
        type: PokemonType.animal,
        subType: "Rat",
        alignment: PokemonAlignment.evil,
        size: 50,
        weight: 3.5,
        hitPoints: 16,
        protection: 2,
        movement: PokemonMovement.normal,
        attack: 5,
        damage: 2,
        defense: 13,
        specialAbilities: [],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Rattatac.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 40,
        name: "Rattatac",
        description: "Rattatac ressemble à un gros rat et possède de petits bras, un corps marron et beige et des pieds palmés.. Rattatac est rapide et robuste, capable de s'attaquer à n'importe qui.",
        level: 4,
        type: PokemonType.animal,
        subType: "Rat",
        alignment: PokemonAlignment.evil,
        size: 50,
        weight: 3.5,
        hitPoints: 16,
        protection: 2,
        movement: PokemonMovement.normal,
        attack: 5,
        damage: 2,
        defense: 13,
        specialAbilities: [],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Rattatac.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 41,
        name: "Salamèche",
        description: "Salamèche est un très jeune dragon au corps rouge. Une flamme brûle au bout de sa queue ; elle flamboie depuis sa naissance.",
        level: 1,
        type: PokemonType.dragon,
        subType: "Dragon rouge",
        alignment: PokemonAlignment.evil,
        size: 60,
        weight: 5,
        hitPoints: 16,
        protection: 0,
        movement: PokemonMovement.normal,
        attack: 8,
        damage: 2,
        defense: 12,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.fire, damage: 2 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Salamèche.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 42,
        name: "Reptincel",
        description: "Reptincel est jeune dragon. Il possède trois grandes et puissantes griffes acérées à chaque main et pied, qui l'aident notamment à déchirer la peau de ses ennemis lors des combats. Il est violent, voire cruel.",
        level: 1,
        type: PokemonType.dragon,
        subType: "Dragon rouge",
        alignment: PokemonAlignment.evil,
        size: 60,
        weight: 5,
        hitPoints: 16,
        protection: 0,
        movement: PokemonMovement.normal,
        attack: 8,
        damage: 2,
        defense: 12,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.intenseFire, damage: 4 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Reptincel.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 43,
        name: "Dracaufeu",
        description: "Dracaufeu est un dragon adulte. Contrairement à ses pré-évolutions, il a deux ailes lui permettant de voler. Sa dentition, avec ses canines apparentes, révèle une préférence marquée pour la viande.",
        level: 3,
        type: PokemonType.dragon,
        subType: "Dragon rouge",
        alignment: PokemonAlignment.evil,
        size: 60,
        weight: 5,
        hitPoints: 16,
        protection: 0,
        movement: PokemonMovement.normal,
        attack: 8,
        damage: 2,
        defense: 12,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.intenseFire, damage: 4 },
            { specialAbility: PokemonSpecialAbility.fireBreath, damage: 12, times: 1 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Dracaufeu.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 44,
        name: "Méga-Dracaufeu",
        description: "Méga-Dracaufeu est un vieu dragon. Il a une allure encore plus bestiale que Dracaufeu. Il ne connait pas la peur et combat à mort.",
        level: 4,
        type: PokemonType.dragon,
        subType: "Dragon rouge",
        alignment: PokemonAlignment.evil,
        size: 60,
        weight: 5,
        hitPoints: 16,
        protection: 0,
        movement: PokemonMovement.normal,
        attack: 8,
        damage: 2,
        defense: 12,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.intenseFire, damage: 4 },
            { specialAbility: PokemonSpecialAbility.fireBreath, damage: 12, times: 1 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Méga-Dracaufeu.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 45,
        name: "Otaria",
        description: "Otaria a l'apparence générale d'un phoque blanc (non pas une otarie, malgré son nom, car il ne possède pas de pattes arrière). Il est le plus souvent vu la langue tirée, et deux grands crocs de sa mâchoire inférieure ressortent de la bouche. Il possède également une corne sur le sommet du crâne.",
        level: 1,
        type: PokemonType.animal,
        subType: "Otarie",
        alignment: PokemonAlignment.good,
        size: 40,
        weight: 4,
        hitPoints: 60,
        protection: 2,
        movement: PokemonMovement.swim,
        attack: 8,
        damage: 2,
        defense: 14,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.cold, damage: 2 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Otaria.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 46,
        name: "Otaria",
        description: "Otaria a l'apparence générale d'un phoque blanc (non pas une otarie, malgré son nom, car il ne possède pas de pattes arrière). Il est le plus souvent vu la langue tirée, et deux grands crocs de sa mâchoire inférieure ressortent de la bouche. Il possède également une corne sur le sommet du crâne.",
        level: 2,
        type: PokemonType.animal,
        subType: "Otarie",
        alignment: PokemonAlignment.good,
        size: 40,
        weight: 4,
        hitPoints: 60,
        protection: 2,
        movement: PokemonMovement.swim,
        attack: 8,
        damage: 2,
        defense: 14,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.cold, damage: 2 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Otaria.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 47,
        name: "Lamantine",
        description: "Lamantine s'inspire du lamantin. Deux crocs de sa mâchoire supérieure sont visibles et sa tête se termine par une corne.",
        level: 3,
        type: PokemonType.animal,
        subType: "Otarie",
        alignment: PokemonAlignment.good,
        size: 40,
        weight: 4,
        hitPoints: 60,
        protection: 2,
        movement: PokemonMovement.swim,
        attack: 8,
        damage: 2,
        defense: 14,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.severeCold, damage: 4 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Lamantine.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 48,
        name: "Lamantine",
        description: "Lamantine s'inspire du lamantin. Deux crocs de sa mâchoire supérieure sont visibles et sa tête se termine par une corne.",
        level: 4,
        type: PokemonType.animal,
        subType: "Otarie",
        alignment: PokemonAlignment.good,
        size: 40,
        weight: 4,
        hitPoints: 60,
        protection: 2,
        movement: PokemonMovement.swim,
        attack: 8,
        damage: 2,
        defense: 14,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.severeCold, damage: 4 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Lamantine.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 49,
        name: "Roucool",
        description: "Roucool est un moineau dodu au corps marron. Ses serres et son bec sont gris rosâtre. Il a des marquages noirs angulaires autour des yeux et une petite crête aux plumes marron et crème sur le dessus de la tête.",
        level: 1,
        type: PokemonType.animal,
        subType: "Moineau",
        alignment: PokemonAlignment.neutral,
        size: 40,
        weight: 2,
        hitPoints: 20,
        protection: 2,
        movement: PokemonMovement.fly,
        attack: 6,
        damage: 2,
        defense: 12,
        specialAbilities: [],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Roucool.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 50,
        name: "Roucoups",
        description: "Roucoups est un gros moineau. Il est couvert de plumes marron, et a un visage et un ventre couleur crème. Son bec et ses pattes sont roses.",
        level: 2,
        type: PokemonType.animal,
        subType: "Moineau",
        alignment: PokemonAlignment.neutral,
        size: 40,
        weight: 2,
        hitPoints: 20,
        protection: 2,
        movement: PokemonMovement.fly,
        attack: 6,
        damage: 2,
        defense: 12,
        specialAbilities: [],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Roucoups.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 51,
        name: "Roucarnage",
        description: "Roucarnage est un très gros moineau qui se sert surtout de ses ailes puissantes pour attaquer.",
        level: 3,
        type: PokemonType.animal,
        subType: "Moineau",
        alignment: PokemonAlignment.neutral,
        size: 40,
        weight: 2,
        hitPoints: 20,
        protection: 2,
        movement: PokemonMovement.fly,
        attack: 6,
        damage: 2,
        defense: 12,
        specialAbilities: [],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Roucarnage.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 52,
        name: "Méga-Roucarnage",
        description: "Méga-Roucarnage est un énorme moineau aux yeux rouge. Les longues plumes sur sa tête se changent en une crête moitié jaune, moitié rose et deux longues plumes roses en sortent (une vers l'avant et une plus longue vers l'arrière).",
        level: 4,
        type: PokemonType.animal,
        subType: "Moineau",
        alignment: PokemonAlignment.neutral,
        size: 40,
        weight: 2,
        hitPoints: 20,
        protection: 2,
        movement: PokemonMovement.fly,
        attack: 6,
        damage: 2,
        defense: 12,
        specialAbilities: [],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Méga-Roucarnage.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 53,
        name: "Sabelette",
        description: "Sabelette ressemble à un pangolin jaune au corps cuirassé. on ventre est complètement beige pâle en plus de son menton. Il possède des yeux noir et bleu et deux petites oreilles.",
        level: 1,
        type: PokemonType.animal,
        subType: "Pangolin",
        alignment: PokemonAlignment.neutral,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Sabelette.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 54,
        name: "Sabelette",
        description: "Sabelette ressemble à un pangolin jaune au corps cuirassé. on ventre est complètement beige pâle en plus de son menton. Il possède des yeux noir et bleu et deux petites oreilles.",
        level: 2,
        type: PokemonType.animal,
        subType: "Pangolin",
        alignment: PokemonAlignment.neutral,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Sabelette.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 55,
        name: "Sablaireau",
        description: "Sablaireau est un Pokémon ressemblant à la fois au blaireau (pattes), au tatou et au pangolin, avec un corps jaune et un ventre blanc pâle. Il possède deux yeux noirs, deux grandes oreilles en pointes et une corne jaune sur la tête. Son dos est hérissé de grosses épines marron allant de la tête jusqu'au bas du dos.",
        level: 3,
        type: PokemonType.animal,
        subType: "Pangolin",
        alignment: PokemonAlignment.neutral,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Sablaireau.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 56,
        name: "Sablaireau",
        description: "Sablaireau est un Pokémon ressemblant à la fois au blaireau (pattes), au tatou et au pangolin, avec un corps jaune et un ventre blanc pâle. Il possède deux yeux noirs, deux grandes oreilles en pointes et une corne jaune sur la tête. Son dos est hérissé de grosses épines marron allant de la tête jusqu'au bas du dos.",
        level: 4,
        type: PokemonType.animal,
        subType: "Pangolin",
        alignment: PokemonAlignment.neutral,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Sablaireau.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 57,
        name: "Cornèbre",
        description: "Cornèbre est un oiseau avec des plumes noires. Son bec jaune et crochu et les trois touffes plumeuses sur le haut de sa tête font respectivement penser à un nez et à un chapeau de sorcière.",
        level: 1,
        type: PokemonType.animal,
        subType: "Corbeau",
        alignment: PokemonAlignment.evil,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.fly,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.darkness, defense: 2 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Cornèbre.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 58,
        name: "Cornèbre",
        description: "Cornèbre est un oiseau avec des plumes noires. Son bec jaune et crochu et les trois touffes plumeuses sur le haut de sa tête font respectivement penser à un nez et à un chapeau de sorcière.",
        level: 2,
        type: PokemonType.animal,
        subType: "Corbeau",
        alignment: PokemonAlignment.evil,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.fly,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.psionist, damage: 3, attack: 2 },
            { specialAbility: PokemonSpecialAbility.darkness, defense: 2 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Cornèbre.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 59,
        name: "Cornèbre",
        description: "Cornèbre est un oiseau avec des plumes noires rappelant les corbeaux. Son bec jaune et crochu et les trois touffes plumeuses sur le haut de sa tête font respectivement penser à un nez et à un chapeau de sorcière.",
        level: 3,
        type: PokemonType.animal,
        subType: "Corbeau",
        alignment: PokemonAlignment.evil,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.fly,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.psionist, damage: 3, attack: 2 },
            { specialAbility: PokemonSpecialAbility.deepDarkness, defense: 4 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Cornèbre.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 60,
        name: "Corboss",
        description: "Corboss est un oiseau bleu foncé avec un plumage qui rappelle une personne habillée en habits formels, plus particulièrement un chef de gang.",
        level: 4,
        type: PokemonType.animal,
        subType: "Corbeau",
        alignment: PokemonAlignment.evil,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.fly,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.psionist, damage: 3, attack: 2 },
            { specialAbility: PokemonSpecialAbility.deepDarkness, defense: 4 },
            { specialAbility: PokemonSpecialAbility.mentalExplosion, damage: 10, times: 1 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Corboss.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 61,
        name: "Fantominus",
        description: "Fantominus n'a pas de vraie forme, ce qui est dû au gaz toxique qui compose 95 % de son corps. Cependant, il apparaît sous la forme d'un Pokémon noir et sphérique entouré d'une brume violette. Il a une large bouche avec deux crocs visibles. Ses yeux semblent dépasser son corps rond.",
        level: 1,
        type: PokemonType.undead,
        subType: "Fantôme",
        alignment: PokemonAlignment.evil,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.fly,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.poison, damage: 3 }
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Fantominus.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 62,
        name: "Spectrum",
        description: "Spectrum ressemble à un fantôme violet avec un corps fait de gaz. Il n'a pas de bras visibles et son corps se termine par une queue dentelée. Ses mains désincarnées ont trois doigts pointus et ses yeux sont larges et triangulaires.",
        level: 2,
        type: PokemonType.undead,
        subType: "Fantôme",
        alignment: PokemonAlignment.evil,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.fly,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Spectrum.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 63,
        name: "Ectoplasma",
        description: "Ectoplasma est un Pokémon bipède violet avec un corps rondouillard. Il a des yeux rouges, une large bouche arborant un rictus sinistre et des oreilles pointues. Il a sur son dos et sur sa tête des piques. Ses bras et ses jambes sont trapus avec trois doigts sur chaque bras et chaque jambe. Il a une petite queue.",
        level: 3,
        type: PokemonType.undead,
        subType: "Fantôme",
        alignment: PokemonAlignment.evil,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.fly,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Ectoplasma.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 64,
        name: "Méga-Ectoplasma",
        description: "Le corps violet aux reflets rougeâtres de Méga-Ectoplasma est parsemé de pointes. Ses oreilles ont gagné en longueur. Ses deux bras et sa queue ont un aspect qui se confond particulièrement avec le reste de son corps.",
        level: 4,
        type: PokemonType.undead,
        subType: "Fantôme",
        alignment: PokemonAlignment.evil,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.fly,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Méga-Ectoplasma.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 65,
        name: "Osselait",
        description: "Osselait est un Pokémon bipède, brun, au visage caché par un crâne sans lequel il n'est jamais vu. Le crâne qu'il porte est celui de sa mère, morte lors de sa naissance.",
        level: 1,
        type: PokemonType.prehistoric,
        subType: "Humanoïde",
        alignment: PokemonAlignment.neutral,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Osselait.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 66,
        name: "Osselait",
        description: "Osselait est un Pokémon bipède, brun, au visage caché par un crâne sans lequel il n'est jamais vu. Le crâne qu'il porte est celui de sa mère, morte lors de sa naissance.",
        level: 2,
        type: PokemonType.prehistoric,
        subType: "Humanoïde",
        alignment: PokemonAlignment.neutral,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Osselait.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 67,
        name: "Ossatueur",
        description: "Ossatueur est un Pokémon bipède de couleur brun foncé. Son ventre est d'une couleur plus claire. Il est reconnaissable à l'apparence osseuse de sa tête. Il a une griffe à chaque main et pied, et se sert d'un os qu'il peut lancer et utiliser comme une arme.",
        level: 3,
        type: PokemonType.prehistoric,
        subType: "Humanoïde",
        alignment: PokemonAlignment.neutral,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Ossatueur.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 68,
        name: "Ossatueur",
        description: "Ossatueur est un Pokémon bipède de couleur brun foncé. Son ventre est d'une couleur plus claire. Il est reconnaissable à l'apparence osseuse de sa tête. Il a une griffe à chaque main et pied, et se sert d'un os qu'il peut lancer et utiliser comme une arme.",
        level: 4,
        type: PokemonType.prehistoric,
        subType: "Humanoïde",
        alignment: PokemonAlignment.neutral,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Ossatueur.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 69,
        name: "Lokhlass",
        description: "Lokhlass est une grande créature marine qui ressemble à un plésiosaure. Son corps est bleu et tacheté, et son ventre est couleur crème. Il a un long cou et de grands yeux noirs. Il a également une petite corne sur le front. Il possède quatre nageoires. Il a une lourde coquille sur le dos.",
        level: 1,
        type: PokemonType.prehistoric,
        subType: "Plésiosaure",
        alignment: PokemonAlignment.good,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Lokhlass.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 70,
        name: "Lokhlass",
        description: "Lokhlass est une grande créature marine qui ressemble à un plésiosaure. Son corps est bleu et tacheté, et son ventre est couleur crème. Il a un long cou et de grands yeux noirs. Il a également une petite corne sur le front. Il possède quatre nageoires. Il a une lourde coquille sur le dos.",
        level: 2,
        type: PokemonType.prehistoric,
        subType: "Plésiosaure",
        alignment: PokemonAlignment.good,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Lokhlass.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 71,
        name: "Lokhlass",
        description: "Lokhlass est une grande créature marine qui ressemble à un plésiosaure. Son corps est bleu et tacheté, et son ventre est couleur crème. Il a un long cou et de grands yeux noirs. Il a également une petite corne sur le front. Il possède quatre nageoires. Il a une lourde coquille sur le dos.",
        level: 2,
        type: PokemonType.prehistoric,
        subType: "Plésiosaure",
        alignment: PokemonAlignment.good,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Lokhlass.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 72,
        name: "Gigamax",
        description: "Gigamax ressemble à un gigantesque Lokhlass. Sa carapace a pris la forme d'un bateau de croisière. Autour de lui flottent de gros cristaux de glace, matérialisant des notes de musique.",
        level: 4,
        type: PokemonType.prehistoric,
        subType: "Plésiosaure",
        alignment: PokemonAlignment.good,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Gigamax.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 73,
        name: "Évoli",
        description: "Évoli est un Pokémon mammalien quadrupède, entre canin et félin, avec une fourrure principalement brune. Le bout de sa queue broussailleuse et son gros col de fourrure sont de couleur crème. Il a de petites jambes minces avec trois petits orteils et un coussinet rose à chaque patte.",
        level: 1,
        type: PokemonType.animal,
        subType: "Mi-canin mi-félin",
        alignment: PokemonAlignment.good,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Évoli.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 74,
        name: "Méga-Évoli",
        description: "Ce Pokémon a maximisé le volume de la fourrure qu'Évoli porte autour du cou, et l'a rendu plus excité.",
        level: 1,
        type: PokemonType.animal,
        subType: "Mi-canin mi-félin",
        alignment: PokemonAlignment.good,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Méga-Évoli.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 75,
        name: "Mentali",
        description: "Mentali ressemble à un chat recouvert d'une fourrure couleur lilas. Cette fourrure à la texture de velours est très sensible et permet au Mentali de sentir les changements de l'air et donc de prédire la météo. Sa queue se divise en deux extrémités.",
        level: 1,
        type: PokemonType.animal,
        subType: "Mi-canin mi-félin",
        alignment: PokemonAlignment.good,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Mentali.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 76,
        name: "Noctali",
        description: "Noctali a des pupilles fendues et un petit museau, ce qui le fait ressembler à un chat noir. En règle générale, le chat noir est  considéré comme un présage de malchance, alors que le Noctali est un véritable signe de chance.",
        level: 1,
        type: PokemonType.animal,
        subType: "Mi-canin mi-félin",
        alignment: PokemonAlignment.good,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Noctali.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 77,
        name: "Nosferapti",
        description: "Nosferapti est une petite chauve-souris. La membrane de ses ailes est violette, tout comme le creux de ses oreilles. Sa mâchoire possède quatre crocs. Il ne possède pas d'yeux, puisqu'il utilise des ultrasons pour se déplacer dans l'obscurité.",
        level: 1,
        type: PokemonType.animal,
        subType: "Chauve-souris",
        alignment: PokemonAlignment.evil,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.fly,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.darkness, defense: 2 },
            { specialAbility: PokemonSpecialAbility.energyAbsorption, damage: 4 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Nosferapti.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 78,
        name: "Nosferapti",
        description: "Nosferapti est une petite chauve-souris. La membrane de ses ailes est violette, tout comme le creux de ses oreilles. Sa mâchoire possède quatre crocs. Il ne possède pas d'yeux, puisqu'il utilise des ultrasons pour se déplacer dans l'obscurité.",
        level: 2,
        type: PokemonType.animal,
        subType: "Chauve-souris",
        alignment: PokemonAlignment.evil,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.fly,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.darkness, defense: 2 },
            { specialAbility: PokemonSpecialAbility.energyAbsorption, damage: 4 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Nosferapti.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 79,
        name: "Nosferalto",
        description: "Nosferalto est une grosse chauve-souris bleu foncé. Il possède de grandes ailes et de minuscules oreilles. Son énorme mâchoire compte quatre crocs. À la différence de sa pré-évolution, il possède des pieds et des yeux.",
        level: 3,
        type: PokemonType.animal,
        subType: "Chauve-souris",
        alignment: PokemonAlignment.evil,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.fly,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.deepDarkness, defense: 4 },
            { specialAbility: PokemonSpecialAbility.energyAbsorption, damage: 4 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Nosferalto.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 80,
        name: "Nostenfer",
        description: "Nostenfer est un Pokémon ressemblant à une chauve-souris dotée d'yeux avec des pupilles rouges, de deux paires d'ailes donnant l'illusion de former une croix ainsi que de pattes atrophiées.",
        level: 4,
        type: PokemonType.animal,
        subType: "Chauve-souris",
        alignment: PokemonAlignment.evil,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.fly,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
            { specialAbility: PokemonSpecialAbility.deepDarkness, defense: 4 },
            { specialAbility: PokemonSpecialAbility.energyAbsorption, damage: 4 },
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Nostenfer.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 81,
        name: "Celebi",
        description: "Celebi est un esprit ressemblant à une fée, il a un corps vert clair, des cheveux à la pointe vert foncé, deux antennes à bout bleu et deux yeux bleus. Il est appelé le Gardien de la forêt.",
        level: 1,
        type: PokemonType.fey,
        subType: "Pétale",
        alignment: PokemonAlignment.good,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Celebi.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 82,
        name: "Celebi",
        description: "Celebi est un esprit ressemblant à une fée, il a un corps vert clair, des cheveux à la pointe vert foncé, deux antennes à bout bleu et deux yeux bleus. Il est appelé le Gardien de la forêt.",
        level: 2,
        type: PokemonType.fey,
        subType: "Pétale",
        alignment: PokemonAlignment.good,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Celebi.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 83,
        name: "Celebi",
        description: "Celebi est un esprit ressemblant à une fée, il a un corps vert clair, des cheveux à la pointe vert foncé, deux antennes à bout bleu et deux yeux bleus. Il est appelé le Gardien de la forêt.",
        level: 3,
        type: PokemonType.fey,
        subType: "Pétale",
        alignment: PokemonAlignment.good,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Celebi.png",
        created: new Date(),
        updated: undefined
    },
    {
        id: 84,
        name: "Celebi",
        description: "Celebi est un esprit ressemblant à une fée, il a un corps vert clair, des cheveux à la pointe vert foncé, deux antennes à bout bleu et deux yeux bleus. Il est appelé le Gardien de la forêt.",
        level: 4,
        type: PokemonType.fey,
        subType: "Pétale",
        alignment: PokemonAlignment.good,
        size: 75,
        weight: 12,
        hitPoints: 24,
        protection: 5,
        movement: PokemonMovement.normal,
        attack: 4,
        damage: 3,
        defense: 10,
        specialAbilities: [
        ],
        specialDefense: PokemonSpecialDefense.none,
        picture: "assets/pokemons/Celebi.png",
        created: new Date(),
        updated: undefined
    },
]